version: '3.8'

services:
  typesense:
    image: typesense/typesense:0.25.1
    ports:
      - "8108:8108"
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY=xyz
      - TYPESENSE_ENABLE_CORS=true
    volumes:
      - typesense_data:/data
    command: '--data-dir /data --api-key=xyz --listen-port 8108 --enable-cors'

  meilisearch:
    image: getmeili/meilisearch:v1.5
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=xyz
      - MEILI_ENV=development
    volumes:
      - meilisearch_data:/meili_data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - SEARCH_BACKEND=typesense
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - TYPESENSE_PROTOCOL=http
      - TYPESENSE_API_KEY=xyz
      - REDIS_URL=redis://redis:6379
    depends_on:
      - typesense
      - redis
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  typesense_data:
  meilisearch_data:
  redis_data:
